---
- hosts: all
  remote_user: ansadmin
  become: yes
  tasks:
      - name: copy the war file 
        copy:
          src: ./*.war
          dest: /opt/
      - name: stop container
        shell: docker stop demo
      - name: remove container
        shell: docker rm -f demo
      - name: container
        shell: docker run -itd --name demo -p 8090:8080 aravindsamsun/javawebapp:latest
